blank_issues_enabled: false
contact_links:
  - name: Feature Request or Bug Report
    url: https://github.com/arshadkazmi42/ifindproduct/discussions
    about: For feature requests or bug reports, start a discussion
